[package]
name = "gml_fmt"
version = "0.9.2"
authors = ["Jack Spira <jjspira@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.33.0"
bitflags = "1.1.0"
fnv = "1.0.6"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "speed_test"
harness = false

[[bin]]
name = "gml_fmt"